[project]
name = "rosalindprobs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "biopython>=1.85",
    "ruff>=0.9.3",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.9.3",
]
