from tkinter.filedialog import askopenfilename


def findMotif(seq, motif):
    n = len(motif)
    index = []
    for nuc in range(len(seq)):
        if seq[nuc : nuc + n] == motif:
            index.append(str(nuc + 1))
    return " ".join(index)


if __name__ == "__main__":
    filename = askopenfilename()
    with open(filename) as f:
        seq = "TACTCTACGCAGCTCTACGCTCTACGTACGCTCTACGCTCTACGTCGATGGGAAAACCTCTACGCTCTACGGGGCTCTACGTAATCGTCTCTACGGCTCTACGGACCTCTACGCGGCTCTACGCTCTACGACTCTACGCCCTCTACGGCAGACTCTACGCCACCGCTCTACGTCTCTACGCCTCTACGCTCTACGCATCTCTACGCATGTCTCTACGCTCTACGTGCTCTACGTCTCTACGCTCTACGGCTCTACGCTCTACGCTCTACGCTCTACGCTCTACGACTCTACGTTTTCTCTACGTGGTCTCTACGTCCAGACTCTACGTCTTGTGCTCTACGTTCACCTCTACGTACTCTACGAGGTCTCTACGCGCTCTACGGGCTCTACGTCTTCCTCGCCTCTACGGCTCACTCTACGCATCACGAGCTCTACGACTCTACGCTCTACGCGACTCTACGCTCTACGTGCTCTACGAGTTCTCTACGCGCATTCTCTACGTGGCTCTACGAGTCTCTACGGGGTCAACTCTACGGGGCACTCTACGCTCTACGCTCTACGCTCTACGGCTCTACGCTCTACGCTCTACGCTCTACGCCCAACGAGCTCTACGCTCTACGACTCTACGCCTCTACGCTCTACGTTCTCTCTACGCTCTACGTTTCTCTACGGCTCTCTACGCTCTACGCTCTACGTTTAACTCTACGAAACTCACTCTACGATCTCTACGTATTTTGTACACTCTACGTGTCAAGACTCTACGTTGCATCTGGCACTCTACGCTCTACGCTTCTCTACGCACTCTACGCTCTACGCCTCTACGT"
        motif = "CTCTACGCT"
        print(findMotif(seq, motif))
